[2024-02-05T16:40:26.945+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-02-05T16:40:25.639418+00:00 [queued]>
[2024-02-05T16:40:26.950+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-02-05T16:40:25.639418+00:00 [queued]>
[2024-02-05T16:40:26.950+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-02-05T16:40:26.954+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): yellow_cabs_upload> on 2024-02-05 16:40:25.639418+00:00
[2024-02-05T16:40:26.957+0000] {standard_task_runner.py:60} INFO - Started process 582 to run task
[2024-02-05T16:40:26.959+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'yellow_cabs_dag', 'yellow_cabs_upload', 'manual__2024-02-05T16:40:25.639418+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/yellow_cabs_project.py', '--cfg-path', '/tmp/tmp6y14ru01']
[2024-02-05T16:40:26.961+0000] {standard_task_runner.py:88} INFO - Job 144: Subtask yellow_cabs_upload
[2024-02-05T16:40:26.981+0000] {task_command.py:423} INFO - Running <TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-02-05T16:40:25.639418+00:00 [running]> on host 66814aa8a277
[2024-02-05T16:40:27.128+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yellow_cabs_dag' AIRFLOW_CTX_TASK_ID='yellow_cabs_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-02-05T16:40:25.639418+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-05T16:40:25.639418+00:00'
[2024-02-05T16:40:46.255+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yellow_cabs_project.py", line 36, in yellow_cabs_upload
    df_iter = pd.read_csv(file_path, index_col=False, chunksize=200000)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
NotADirectoryError: [Errno 20] Not a directory: '/opt/airflow/dags/yellow_cabs_project.py/csv_file.csv'
[2024-02-05T16:40:46.262+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=yellow_cabs_dag, task_id=yellow_cabs_upload, execution_date=20240205T164025, start_date=20240205T164026, end_date=20240205T164046
[2024-02-05T16:40:46.288+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 144 for task yellow_cabs_upload ([Errno 20] Not a directory: '/opt/airflow/dags/yellow_cabs_project.py/csv_file.csv'; 582)
[2024-02-05T16:40:46.353+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-05T16:40:46.451+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
