[2024-02-09T23:54:24.615+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-02-09T23:54:23.878402+00:00 [queued]>
[2024-02-09T23:54:24.619+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-02-09T23:54:23.878402+00:00 [queued]>
[2024-02-09T23:54:24.619+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-02-09T23:54:24.625+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): yellow_cabs_upload> on 2024-02-09 23:54:23.878402+00:00
[2024-02-09T23:54:24.630+0000] {standard_task_runner.py:60} INFO - Started process 2946 to run task
[2024-02-09T23:54:24.632+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'yellow_cabs_dag', 'yellow_cabs_upload', 'manual__2024-02-09T23:54:23.878402+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/yellow_cabs_project.py', '--cfg-path', '/tmp/tmp1p9xsb1c']
[2024-02-09T23:54:24.635+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask yellow_cabs_upload
[2024-02-09T23:54:24.812+0000] {task_command.py:423} INFO - Running <TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-02-09T23:54:23.878402+00:00 [running]> on host fa2aaf479b3c
[2024-02-09T23:54:24.842+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yellow_cabs_dag' AIRFLOW_CTX_TASK_ID='yellow_cabs_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-02-09T23:54:23.878402+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-09T23:54:23.878402+00:00'
[2024-02-09T23:55:59.886+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yellow_cabs_project.py", line 21, in yellow_cabs_upload
    result = wget.download(f'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-{month}.parquet')
  File "/home/airflow/.local/lib/python3.8/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/usr/local/lib/python3.8/urllib/request.py", line 286, in urlretrieve
    raise ContentTooShortError(
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 37187364 out of 38139949 bytes>
[2024-02-09T23:55:59.909+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=yellow_cabs_dag, task_id=yellow_cabs_upload, execution_date=20240209T235423, start_date=20240209T235424, end_date=20240209T235559
[2024-02-09T23:55:59.924+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task yellow_cabs_upload (<urlopen error retrieval incomplete: got only 37187364 out of 38139949 bytes>; 2946)
[2024-02-09T23:55:59.943+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-09T23:55:59.953+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
