[2024-01-31T19:19:04.670+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-01-31T19:19:03.581417+00:00 [queued]>
[2024-01-31T19:19:04.675+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-01-31T19:19:03.581417+00:00 [queued]>
[2024-01-31T19:19:04.676+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-31T19:19:04.680+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): yellow_cabs_upload> on 2024-01-31 19:19:03.581417+00:00
[2024-01-31T19:19:04.683+0000] {standard_task_runner.py:60} INFO - Started process 65 to run task
[2024-01-31T19:19:04.685+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'yellow_cabs_dag', 'yellow_cabs_upload', 'manual__2024-01-31T19:19:03.581417+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/yellow_cabs_project.py', '--cfg-path', '/tmp/tmpih1n51zp']
[2024-01-31T19:19:04.687+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask yellow_cabs_upload
[2024-01-31T19:19:04.708+0000] {task_command.py:423} INFO - Running <TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-01-31T19:19:03.581417+00:00 [running]> on host 8ff05e883b9e
[2024-01-31T19:19:04.830+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yellow_cabs_dag' AIRFLOW_CTX_TASK_ID='yellow_cabs_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-01-31T19:19:03.581417+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-31T19:19:03.581417+00:00'
[2024-01-31T19:19:10.842+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yellow_cabs_project.py", line 28, in yellow_cabs_upload
    df = pd.to_csv(merged)
AttributeError: module 'pandas' has no attribute 'to_csv'
[2024-01-31T19:19:10.863+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=yellow_cabs_dag, task_id=yellow_cabs_upload, execution_date=20240131T191903, start_date=20240131T191904, end_date=20240131T191910
[2024-01-31T19:19:10.897+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task yellow_cabs_upload (module 'pandas' has no attribute 'to_csv'; 65)
[2024-01-31T19:19:10.949+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-31T19:19:11.039+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
